version: '3.8'
services:
  api:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
  worker:
    build: .
    command: node dist/workers/processUpload.js
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7

volumes:
  pgdata:
